# Port MQTT standard
listener 1883

# Port WebSocket
listener 9001

# Autoriser les connexions anonymes (pour les tests)
allow_anonymous true

# Configuration des logs
log_dest file /mosquitto/log/mosquitto.log
log_type all

# Persistance des données
persistence true
persistence_location /mosquitto/data/
